name: Update remote resources

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: 'Resources/**'

jobs:
  update-remote-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
          PR_LABELS: |
            Sync
          ASSIGNEES: qrtDaniil
